Add a buffer duration setting to popup and send it to profiler
firefox-devtools/Gecko-Profiler-Addon pull request #130
Opened 2018-10-24 12:15 UTC by canaltinova

We are changing the profiler API and adding a field named `bufferDuration` to start parameters. See [Bug 1476775](https://bugzilla.mozilla.org/show_bug.cgi?id=1476775). After the mozilla-central side lands, we have to land this part and package the add-on.

This is pretty much same with the new performance tab part of mozilla-central side patch. Adding the same reviewers. (https://phabricator.services.mozilla.com/D6268)

2018-10-24 12:18 UTC, canaltinova commented on popup.css
> +  grid-template-columns: 8em auto;
The `Buffer Duration:` text was breaking to the next line. So I had to increase it by one to prevent that.

2018-10-24 12:18 UTC, canaltinova commented on popup.js
> +const bufferdurationScale = makeExponentialScale(1, 200);
Still don't know what should be the max number here :)

2018-10-24 13:43 UTC, mstange commented
I have a few requests:
 - Rename "Buffer size" to "Max buffer size"
 - Move "Buffer duration" before "Max buffer size"
 - Rename "Buffer duration" to "Window length"
 - Store the maximum buffer size in a new setting, discard any existing setting for the buffer size, and make the new default 270MB
 - Make the last notch of the buffer duration setting be ∞ (no duration restriction)

I'd like to somehow convey the fact that the maximum buffer size restriction overrides the window length setting, so that users know that setting the window length to infinity won't consume all their memory. I think that my suggested changes might be enough to get this point across: The word "max" sounds overriding, and "Max buffer size" comes last in the list.

I'd also like to convey that the fixed duration profiling mode is the recommended default profiling workflow, and that a fixed buffer size profiling mode is discouraged but still possible.

2018-10-26 19:37 UTC, gregtatum requested changes

2018-10-26 19:37 UTC, gregtatum commented on popup.html
> +      <h1 class="settings-setting-label">Buffer duration:</h1>
I think we need some way to be able to tell if the browser supports the buffer duration parameter, and have this UI hidden if it's not supported. I'm not sure anything is exposed in web extension API already that has that information already.

2018-11-01 11:49 UTC, canaltinova commented
Thank you Markus and Greg for the review. Addressed your comments. It's ready for another review

2018-11-07 16:02 UTC, canaltinova commented
Implementation of `∞` duration was a bit hacky. Changed it a bit.

2018-11-07 20:36 UTC, mstange commented
I'm really sorry about this, but could you revert the change to bufferSize / maxBufferSize again? Now that [bug 1476757](https://bugzilla.mozilla.org/show_bug.cgi?id=1476757) has been backed out, it's the actual buffer size again, so I think we shouldn't change its default size after all.

2018-11-08 16:33 UTC, canaltinova commented
@mstange yeah, you're right. Changed back the `maxBufferSize` changes.

2018-11-09 17:14 UTC, julienw approved these changes
Thanks for the patch, this is exciting!

I left 2 comments that I'd like to see fixed. Thanks again!

2018-11-09 17:14 UTC, julienw commented on popup.js
> +    .forEach(el => (el.style.display = windowLengthVisibility));
This is optional given the amount of reviews you already got, but I'd do it differently: I'd simply add a class `no-windowlength` or `has-windowlength` (depending on how you want to implement it) to `document.body` and define the visibility directly in CSS.  The reason is that it's easier to change and reason about if we change the class names or the structure of the document in the future.

2018-11-09 17:14 UTC, julienw commented on popup.js
> +  } sec`;
I think that for `∞` we shouldn't have the unit `sec`.

2018-11-12 11:41 UTC, canaltinova commented on popup.js
> +    .forEach(el => (el.style.display = windowLengthVisibility));
Yeah, you're right. Changed it :)

2018-11-14 21:52 UTC, mstange approved these changes

2018-11-26 10:32 UTC, merged