Ported profiler to a WebExtension
firefox-devtools/Gecko-Profiler-Addon pull request #44
Opened 2017-04-27 17:39 UTC by squarewave

Unfortunately the diff is a bit of a nightmare. Anyone interested can however look to https://github.com/squarewave/gecko-profiler-webextension for a *slightly* more understandable commit log.

Some highlights:
- This uses a new geckoProfiler WebExtension API which should be landing on Nightly shortly.
- This does not yet support profiling remote tabs. Remote profiling was working for a while with the experimental WebExtension API, but to make it official we'll need to extend the devtools API to support custom panels in WebIDE (really in about:debugging once WebIDE is dead.)
- I had to remap <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+{<kbd>1</kbd>,<kbd>2</kbd>} to <kbd>Alt</kbd>+{<kbd>1</kbd>,<kbd>2</kbd>} due to the WebExtensions commands API seeming to not work with multiple modifiers. I'm going to try to investigate why shortly and potentially file a bug.

2017-04-27 17:47 UTC, mstange commented
The keyboard shortcut change is unfortunate. It would be really good to find a way to avoid it.

2017-04-27 18:10 UTC, mstange commented
In terms of updates, updating an SDK-based add-on to a WebExtension seems to be no problem at all - we just need to point the update.rdf file at a different URL.

However, it's not possible to update to an add-on with a different ID. So either we need to keep the ID `jid0-edalmuivkozlouyij0lpdx548bc@jetpack`, or we need to do something more sophisticated:
 1. Land + package + sign the WebExtension with the ID `geckoprofiler@mozilla.com`, but keep around the old add-on.
 2. Create a bootstrapped add-on (not SDK-based) with the ID `jid0-edalmuivkozlouyij0lpdx548bc@jetpack`, whose sole function is to download and install the new WebExtension add-on, and then uninstall itself.
 3. Make the current update.rdf point at that bootstrapped add-on, remove the old add-on.
 4. The update.rdf for the WebExtension add-on will need to live at a slightly different URL.

2017-04-27 18:17 UTC, andymckay commented
What is the reason for wanting to change the ID?

2017-04-27 18:19 UTC, kmaglione commented
@mozilla.com and @mozilla.org IDs have special protections on AMO, and the profiler API is currently protected by a whitelist of APIs that can access it. I really don't want to add a jid0-a-bunch-of-nonsense@jetpack ID to that list.

2017-04-27 18:45 UTC, andymckay commented
It's easy enough to add one or two add-ons to the list on AMO. I'm assuming that the hard coding of ids is a temporary solution until we've got a unified solution coming out of https://bugzilla.mozilla.org/show_bug.cgi?id=1280235. If not, wouldn't mind talking about that more so we don't end up with competing systems.

2017-04-27 18:55 UTC, kmaglione commented
Yes, it's meant as a temporary solution, but at this point, getting the profiler off of the SDK is too important to block on that.

2017-04-27 18:57 UTC, andymckay commented
Awesome, all cool with me then. 👍

2017-04-28 17:22 UTC, squarewave commented
I updated the commit to leave the old xpi and update.rdf files intact, but created a new directory called transtion. This has the code as outlined above to install a temporary add-on which will simply try to install the new add-on and, if successful, uninstall itself.

Unfortunately I'm still stuck on the keyboard shortcut issue.

2017-04-28 19:14 UTC, mstange requested changes

2017-04-28 19:14 UTC, mstange commented on resources/panel-container.html
> -<!DOCTYPE html>
I would like to keep this file around because it helps when playing with the popup design.

2017-04-28 19:14 UTC, mstange commented on popup.js
> -  self.port.emit('ProfilerControlEvent', { type: 'PanelHeightUpdated', height });
How do you handle resizing the popup when the settings are expanded?

2017-04-28 19:14 UTC, mstange commented on transition/install.rdf
> +        <em:updateURL>https://raw.githubusercontent.com/devtools-html/Gecko-Profiler-Addon/master/gecko_profiler.update.rdf</em:updateURL>
The transition add-on shouldn't need to be updated, right? So this is just a last resort if we screwed something up. And I think it'll need to point to `.../master/transition/gecko_profiler.update.rdf`.

2017-04-28 19:14 UTC, mstange commented on content.js
> +        getSymbolTable: (debugName, breakpadId) => getSymbolTable(debugName, breakpadId),
I think this line can be just `getSymbolTable,`.

2017-04-28 19:14 UTC, mstange commented on content.js
> +        console.log('success ' + debugName);
let's remove this line

2017-04-28 19:14 UTC, mstange commented on content.js
> +      const { resolve, reject } = symbolReplyPromiseMap.get([debugName, breakpadId].join(':'));
Should we remove the entry from the map here? Probably.

2017-04-28 19:14 UTC, mstange commented on .web-extension-id
> +geckoprofiler@mozilla.com
The comment sounds like a lie :)

2017-04-28 19:14 UTC, mstange commented on background.js
> +  }
I'm not sure what this is trying to do. But we shouldn't change the profiler state when the add-on starts. For example, when doing startup profiling using the `MOZ_PROFILER_STARTUP` env variable, the profiler will already be running by the time the add-on is initialized, and we don't want to throw away the profiler buffer contents by stopping the profiler here.

2017-04-28 19:16 UTC, mstange commented on transition/bootstrap.js
> +// NOTE: this file's only purpose is to be packaged into gecko_profiler_shim.xpi,
@kmaglione, could you review this file? Thanks!

2017-04-28 21:44 UTC, squarewave commented on .web-extension-id
> +geckoprofiler@mozilla.com
It's certainly a lie, but I'm not the one who told it, since I never touched this file.

2017-04-28 21:47 UTC, squarewave commented on background.js
> +  }
Eh, it was an attempt at making sure issue #10 is resolved, but that's a good point - I'll scrap it.

2017-05-01 20:13 UTC, mstange commented
Ehsan reminded me of something that I hadn't thought of before: We'd like to keep the ability to profile release versions of Firefox, which do not have the profiler WebExtensions API. So we can't update all installations of the old add-on to the shim add-on.
I'm not sure what to do about that.

2017-05-01 20:49 UTC, mikeconley commented
I'm guessing we'll want the gecko_profiler.update.rdf to offer up the SDK based Gecko Profiler Add-on for 54 and under, and the bootstrap / replacement add-on for 55+. Any holes in that plan?

2017-05-01 20:58 UTC, squarewave commented
Quick update on this: I've got a patch waiting for review in [Bug 1337545](https://bugzilla.mozilla.org/show_bug.cgi?id=1337545) which fixes the shortcuts issue to allow <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd> and friends.

2017-05-03 17:47 UTC, squarewave commented
The fix for shortcuts is r+ and just waiting to be landed, so I put the fixup commit here. Quick question, do we care about slightly out-of-date Nightly versions that still don't have the geckoProfiler API? Otherwise mikeconley's suggestion should work, which I've implemented in the latest commit.

2017-05-03 17:48 UTC, squarewave commented on popup.js
> -  self.port.emit('ProfilerControlEvent', { type: 'PanelHeightUpdated', height });
The browserAction API handles that for you, which is nice :)

2017-05-03 19:27 UTC, kmaglione commented on transition/bootstrap.js
> +// NOTE: this file's only purpose is to be packaged into gecko_profiler_shim.xpi,
Looks good to me.

2017-05-03 19:29 UTC, mstange requested changes
Looks good except for the minVersion thing and the xpi filenames.

Let me make sure I understand what xpis we'll have in which places after this change.
 - `/gecko_profiler.xpi` is the SDK-based add-on.
 - `/gecko_profiler_shim.xpi` is the transition add-on.
 - `/gecko_profiler-0.1.xpi` / `/gecko_profiler-0.3.xpi` is the WebExtension add-on.

I think we should change this so that:
 - `/gecko_profiler.xpi` is the WebExtension add-on.
 - `/gecko_profiler_transition.xpi` is the transition add-on.
 - `/gecko_profiler_legacy.xpi` is the SDK-based add-on.

2017-05-03 19:29 UTC, mstange commented on transition/install.rdf
> +        <em:optionsURL>data:text/xml,&lt;placeholder/&gt;</em:optionsURL>
What does this do? Is there a way to indicate "no options"?

2017-05-03 19:29 UTC, mstange commented on transition/install.rdf
> +                <em:minVersion>38.0a1</em:minVersion>
I think this should be 55.0a1. We don't want to allow installing the transition add-on on Firefox versions that don't support the web extension.

2017-05-03 19:29 UTC, mstange commented on updates.json
> +      { "version": "0.3", "update_link": "https://raw.githubusercontent.com/devtools-html/Gecko-Profiler-Addon/master/gecko_profiler-0.3.xpi" }
What does this do? Is it used as a source of information when generating the update.rdf file? In any case, let's not make the version number part of the filename.

2017-05-03 19:29 UTC, mstange commented on transition/bootstrap.js
> +const NEW_ADDON_XPI_URL = "https://raw.githubusercontent.com/devtools-html/Gecko-Profiler-Addon/master/gecko_profiler-0.1.xpi";
I think we should remove the version number from the filename.

2017-05-03 19:42 UTC, mstange commented
> I'm guessing we'll want the gecko_profiler.update.rdf to offer up the SDK based Gecko Profiler Add-on for 54 and under, and the bootstrap / replacement add-on for 55+. Any holes in that plan?

I didn't know that you could offer different files to different target application versions. That's great, so I think that plan will work.

2017-05-03 20:39 UTC, squarewave commented
@mstange, were you planning on signing the transition xpi before merging this? I wasn't intending this commit to shift everything over all in one go, but if that was your plan I can do it so long as I have that xpi. The reason I mention this is if you want the WebExtension xpi to keep the `gecko_profiler.xpi` name, I don't want to have users download that and get an error because the existing update.rdf file points to it. So if we want this commit to actually switch users over, we need:

- The signed transition XPI as mentioned, which will need to be under `gecko_profiler_transition.xpi`
- The update.rdf file under `transition` will instead need to replace the `gecko_profiler.update.rdf` file in the root
- We'll need to make sure the shortcuts fix has landed for some amount of time before merging this so we don't temporarily eliminate people's profiler shortcuts.

2017-05-03 21:00 UTC, mstange commented
Yes, I was planning on signing the XPIs before merging this PR. I can send the signed files to you, or I could just commit them on top of our branch.

2017-05-03 21:56 UTC, mstange approved these changes
Looks good to me now! Let's merge it on Friday.

2017-05-03 21:56 UTC, mstange commented on README.md
> + - <kbd>Alt</kbd>+<kbd>2</kbd>: Capture the profile. This captures the current contents of the profiler buffer, opens a tab with perf-html at `https://perf-html.io/`, and sends the profile to it.
This can be reverted again.

2017-05-06 18:46 UTC, merged